#!/usr/bin/env python3
"""명령 정의의 단일 진실. 도움말과 README 명령 블록을 여기서 생성한다.

같은 사실이 네 곳(`cli.py` 디스패치 · `bin/jig` 도움말 · `README.md` ·
`README.ko.md`)에 살면 반드시 어긋난다. 가정이 아니다 — **최초 커밋부터**
`cli.py` 는 `build`·`budget`·`growth`·`golden` 을 받았는데 `bin/jig` 도움말은
한 번도 그것들을 실은 적이 없다. 그 뒤 도움말을 4번 고쳤는데도 안 맞춰졌다.

검사로 잡는 대신 **어긋날 곳을 없앤다.** 이 표에서 세 곳을 생성한다.

생성은 런타임이 아니라 **커밋되는 코드 생성**이다. `bin/jig` 의 도움말은 순수 bash 로
남아야 한다 — `new` 와 `help` 는 PyYAML 없이 동작하도록 일부러 bash 에서 처리하고,
bootstrap.sh 의 존재 이유가 "의존성이 없을 때도 안내가 나와야 한다" 이다. 런타임에
파이썬으로 만들면 PyYAML 이 없을 때 도움말 대신 트레이스백이 나온다.
"""
from __future__ import annotations

import unicodedata
from pathlib import Path

try:
    from . import mdblock
except ImportError:  # 스크립트로 직접 불릴 때 (adapters 를 패키지로 import 하지 않는 경로)
    import mdblock  # type: ignore[no-redef]

HARNESS = Path(__file__).resolve().parents[1]

GROUPS = [
    ("core", "", ""),
    ("skills", "skill sources", "스킬 소스"),
    ("stacks", "stacks — what a project gets set up with", "스택 — 프로젝트에 무엇을 세팅하는가"),
    ("dev", "working on jigkit", "jigkit 자체를 고칠 때"),
]

COMMANDS = [
    # core
    ("core", "<profile> [project]", "<프로필> [프로젝트]",
     "start a session for that profile", "해당 프로필로 Claude 세션을 연다"),
    ("core", "list", "list",
     "profiles, with skill / agent / MCP counts", "프로필 목록 (스킬·에이전트·MCP 개수)"),
    ("core", "build [profile]", "build [프로필]",
     "compile into build/claude/<name>/", "build/claude/<name>/ 으로 컴파일"),
    ("core", "doctor [profile]", "doctor [프로필]",
     "check rules and the handoff graph", "규칙과 핸드오프 사슬 검사"),
    ("core", "budget [profile]", "budget [프로필]",
     "measure session-start tokens against the cap", "기동 토큰 실측 + 상한 대조"),
    ("core", "growth 0 10 25 50", "growth 0 10 25 50",
     "measure the cost curve for N skills", "스킬 N개일 때의 비용 곡선 실측"),
    ("core", "golden [--update]", "golden [--update]",
     "regression-test the compiler", "컴파일러 회귀 검사"),
    ("core", "argv <profile>", "argv <프로필>",
     "print the launch argv without running it", "기동 인자만 출력 (실행하지 않음)"),
    ("core", "new <name>", "new <이름>",
     "scaffold a profile", "템플릿에서 새 프로필 생성"),
    ("core", "lang [language]", "lang [언어]",
     "set the response language in the global instructions",
     "전역 지침의 응답 언어를 바꾼다 (인자 없으면 현재 값)"),
    # skills
    ("skills", "source add <url> [--as N]", "source add <url> [--as N]",
     "register a skill repository (link + SHA only)", "오픈소스 스킬 저장소 등록 (링크 + SHA 만)"),
    ("skills", "source list", "source list",
     "registered sources and sync state", "등록된 소스와 동기화 상태"),
    ("skills", "sync [source]", "sync [소스]",
     "fetch to the pinned commit", "등록된 ref 대로 캐시를 맞춘다"),
    ("skills", "sync --check", "sync --check",
     "is there an update? touches nothing", "최신 SHA 만 확인 (캐시·등록부 불변)"),
    ("skills", "sync --update [source]", "sync --update [소스]",
     "apply, showing what changed", "최신으로 올리고 무엇이 바뀌었는지 보여준다"),
    ("skills", "skills [pattern]", "skills [패턴]",
     "what is available, and what it costs", "쓸 수 있는 스킬과 설명 토큰 비용"),
    ("skills", "usage [--project P] [--profile N]", "usage [--project P] [--profile N]",
     "what actually got invoked, across all projects", "무엇이 실제로 불렸는지 (전 프로젝트 합산)"),
    # stacks
    ("stacks", "stack list", "stack list",
     "the catalog — tools by language and role", "카탈로그 — 언어별·기능별 도구"),
    ("stacks", "stack show <id> [--with a,b]", "stack show <id> [--with a,b]",
     "what that combination places", "그 조합이 무엇을 배치하는지"),
    ("stacks", "stack show <id> --plan [dir]", "stack show <id> --plan [디렉터리]",
     "the commands to run, in order", "실행할 명령 목록 (순서대로)"),
    ("stacks", "stack apply <id> [project] [--apply]", "stack apply <id> [프로젝트] [--apply]",
     "place hooks, config and MCP definitions", "훅·설정·MCP 정의를 배치 (기본 dry-run)"),
    ("stacks", "stack check <id> [project]", "stack check <id> [프로젝트]",
     "declared against actual", "선언 ↔ 실제 대조"),
    # dev
    ("dev", "touched [range]", "touched [범위]",
     "which docs mention what this change touched", "이 변경이 건드린 개념을 언급하는 문서"),
    ("dev", "docs --check", "docs --check",
     "are the generated command blocks current?", "생성된 명령 블록이 최신인지"),
    ("dev", "selftest", "selftest",
     "unit-test the gates, doc routing and generated docs", "게이트·문서 라우팅·생성물 검사"),
]

# 마커는 **렌더링에 보이지 않는 주석**이어야 한다.
# bin/jig 는 bash 주석(heredoc 밖), README 는 HTML 주석.
_TAG = "jig commands (generated by `jig docs --update`)"
TARGETS = {
    "bin/jig": (f"    # >>> {_TAG} >>>", "    # <<< jig commands <<<"),
    "README.md": (f"<!-- >>> {_TAG} >>> -->", "<!-- <<< jig commands <<< -->"),
    "docs/ko/README.md": (f"<!-- >>> {_TAG} >>> -->", "<!-- <<< jig commands <<< -->"),
}

# 번역은 `docs/<lang>/` 에 산다. 글롭으로 훑지 않는 이유는 COMMANDS 표가 en·ko 두
# 언어의 문자열만 갖고 있기 때문이다 — 표에 없는 언어 디렉터리를 자동으로 잡으면
# 영어 블록을 조용히 써 넣는다. 언어를 늘리려면 표와 여기를 같이 늘린다.
KO_PREFIX = "docs/ko/"


def names() -> list[str]:
    """디스패치 가능한 명령 이름. 사용법 문자열도 여기서 만든다 —
    손으로 유지하면 또 어긋난다(`selftest` 가 실제로 그렇게 빠져 있었다)."""
    seen: list[str] = []
    for _, inv, _, _, _ in COMMANDS:
        head = inv.split()[0]
        if not head.startswith("<") and head not in seen:
            seen.append(head)
    return seen


def usage_line() -> str:
    return "사용법: jig <프로필> [프로젝트] | " + " | ".join(names())


def _w(s: str) -> int:
    """터미널 표시 폭. 한글은 두 칸을 차지하므로 len() 으로는 정렬이 안 맞는다."""
    return sum(2 if unicodedata.east_asian_width(c) in "WF" else 1 for c in s)


def _pad(s: str, width: int) -> str:
    return s + " " * max(1, width - _w(s))


def _rows(ko: bool) -> list[tuple[str, str, str]]:
    out = []
    for group, inv_en, inv_ko, en, kodesc in COMMANDS:
        out.append((group, f"jig {inv_ko if ko else inv_en}", kodesc if ko else en))
    return out


def render_help() -> str:
    """bin/jig 의 heredoc 전체 (한국어)."""
    rows = _rows(ko=True)
    width = max(_w(inv) for _, inv, _ in rows) + 3
    lines = ["jig — 프로필 하네스 (jigkit)"]
    for group, _, header_ko in GROUPS:
        mine = [(i, d) for g, i, d in rows if g == group]
        if not mine:
            continue
        lines.append("")
        if header_ko:
            lines.append(header_ko)
        for inv, desc in mine:
            lines.append("  " + _pad(inv, width) + desc)
    return "\n".join(lines)


def render_md(ko: bool) -> str:
    """README 의 명령 블록 (```bash 펜스 포함)."""
    rows = _rows(ko)
    width = max(_w(inv) for _, inv, _ in rows) + 3
    lines = ["```bash"]
    for group, header_en, header_ko in GROUPS:
        mine = [(i, d) for g, i, d in rows if g == group]
        if not mine:
            continue
        header = header_ko if ko else header_en
        if header:
            lines.append("")
            lines.append(f"# {header}")
        for inv, desc in mine:
            lines.append(_pad(inv, width) + "# " + desc)
    lines.append("```")
    return "\n".join(lines)


def rendered(target: str) -> str:
    if target == "bin/jig":
        return "    cat <<'USAGE'\n" + render_help() + "\nUSAGE"
    return render_md(ko=target.startswith(KO_PREFIX))


def apply(write: bool) -> list[str]:
    """마커 사이를 다시 쓴다. 바뀐(또는 바뀌어야 할) 파일 목록을 돌려준다."""
    return [
        target
        for target, markers in TARGETS.items()
        if mdblock.apply_block(HARNESS / target, markers, rendered(target), write)
    ]
