#!/usr/bin/env python3
"""스택 카탈로그. 도구 중립 — Claude Code 문법을 모른다.

`library/stacks/*.yaml` 하나에서 **카탈로그 문서 · `jig stack` 출력 · 배치 절차**가 모두
나온다. 문서와 동작을 따로 쓰면 어긋나기 때문이다(`commands.py` 가 생긴 것과 같은 이유).

이 파일은 **아무것도 쓰지 않는다.** 파일을 쓰는 것은 `adapters/claude/stack_apply.py` 뿐이다 —
경계가 그렇게 그어져 있어서 `list`·`show`·`show --plan`·`check` 는 어디서 돌려도 안전하다.
"""
from __future__ import annotations

import json
import re
import shlex
import tomllib
from pathlib import Path

import yaml

HARNESS = Path(__file__).resolve().parents[1]
STACKS = HARNESS / "library" / "stacks"
MCP_DIR = HARNESS / "library" / "mcp"

# 카탈로그 표의 "기능별" 축. 여기 없는 role 은 로드가 거부한다 — 자유 문자열이면
# `lint`/`linting`/`format` 이 섞여 표가 조용히 갈라진다.
ROLES = [
    "runtime", "lint", "types", "test", "framework", "backend", "db", "ui",
    "e2e", "mobile", "observability", "security", "analytics", "design",
    "container", "perf",
]
SURFACES = ["mcp", "agents", "hook", "gate", "library"]

MARKERS = (
    "<!-- >>> jig stacks (generated by `jig docs --update`) >>> -->",
    "<!-- <<< jig stacks <<< -->",
)
CATALOG = STACKS / "README.md"

# 대상 프로젝트의 훅 디스패처 안에서 생성물 구간을 두르는 마커. 배치(stack_apply)와
# 대조(check)가 **같은 구간을 봐야** 한다 — 그래서 한 곳에 둔다.
HOOK_MARKERS = ("# >>> jig stack (generated by `jig stack apply`) >>>",
                "# <<< jig stack <<<")
ID_COMMENT = re.compile(r"#\s*([A-Za-z0-9_.@/-]+)\s*$")


class StackError(Exception):
    """정의가 어긋난 경우. 조용히 넘어가지 않는다."""


# ---------------------------------------------------------------- 로드와 검증

def _read(path: Path) -> dict:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as e:
        raise StackError(f"{path.name} 파싱 실패: {e}") from e
    if not isinstance(data, dict):
        raise StackError(f"{path.name}: 최상위가 매핑이 아니다")
    return data


def _items_of(block: dict) -> list[dict]:
    items = block.get("items") or []
    if not isinstance(items, list):
        raise StackError("items 가 목록이 아니다")
    return items


def _validate_item(item: dict, where: str) -> None:
    for field in ("id", "role", "surface"):
        if not item.get(field):
            raise StackError(f"{where}: {field} 가 없다 — {item}")
    if item["role"] not in ROLES:
        raise StackError(f"{where}: 모르는 role {item['role']!r} (ROLES 에 추가해야 한다)")
    if item["surface"] not in SURFACES:
        raise StackError(f"{where}: 모르는 surface {item['surface']!r}")
    surface = item["surface"]
    if surface == "hook":
        hook = item.get("hook") or {}
        if not hook:
            raise StackError(f"{where}: surface: hook 인데 hook 정의가 없다 — {item['id']}")
        # 이벤트당 디스패처가 하나라는 전제 위에 배치가 서 있다. 다른 이벤트를 쓰려면
        # 디스패처를 하나 더 만들어야 하므로 조용히 받지 않는다.
        if hook.get("event", "PostToolUse") != "PostToolUse":
            raise StackError(f"{where}: hook.event 는 PostToolUse 만 지원한다 — {item['id']}")
        if not hook.get("ext") or not hook.get("run"):
            raise StackError(f"{where}: hook 에 ext·run 이 필요하다 — {item['id']}")
    if surface == "gate":
        gate = item.get("gate") or {}
        if not gate:
            raise StackError(f"{where}: surface: gate 인데 gate 정의가 없다 — {item['id']}")
        if not gate.get("run"):
            # 여기서 안 잡으면 apply 때 KeyError 트레이스백으로 나온다.
            raise StackError(f"{where}: gate 에 run 이 필요하다 — {item['id']}")
    if surface == "mcp":
        if not item.get("mcp"):
            raise StackError(f"{where}: surface: mcp 인데 mcp 정의가 없다 — {item['id']}")
        # MCP 정의는 `library/mcp/<id>.json` 으로 나간다. detect 가 다른 이름을 보면
        # 배치가 성공해도 check 가 영원히 "감지 실패" 를 낸다 (실제로 그랬다).
        named = (item.get("detect") or {}).get("mcp")
        if named and named != item["id"]:
            raise StackError(
                f"{where}: detect.mcp({named}) 가 id({item['id']}) 와 다르다 — "
                f"MCP 정의 파일 이름은 id 다"
            )
    if not item.get("why"):
        raise StackError(f"{where}: why 가 없다 — {item['id']}. 근거 없는 항목은 취향이다")


def load() -> tuple[dict[str, dict], dict[str, dict]]:
    """(스택, 프리셋). 어긋난 정의는 여기서 전부 실패시킨다."""
    stacks: dict[str, dict] = {}
    seen_ids: dict[str, str] = {}

    for path in sorted(STACKS.glob("*.yaml")):
        if path.name == "presets.yaml":
            continue
        data = _read(path)
        name = data.get("name")
        if not name:
            raise StackError(f"{path.name}: name 이 없다")
        blocks = [("base", {"items": data.get("base") or []})]
        optional = data.get("optional") or {}
        blocks += [(f"optional.{k}", v or {}) for k, v in optional.items()]
        strippable = data.get("strippable") or {}
        for where, block in blocks:
            # 오타난 strips 키는 조용히 아무것도 지우지 않는다 — ESLint 가 Biome 옆에
            # 그대로 남는다. 다른 어긋남과 같은 자리(로드 시점)에서 잡는다.
            for sid in block.get("strips") or []:
                if sid not in strippable:
                    raise StackError(
                        f"{path.name}:{where}: strips 의 {sid!r} 를 strippable 에서 못 찾았다"
                    )
            for item in _items_of(block):
                _validate_item(item, f"{path.name}:{where}")
                # 같은 도구가 두 곳에 정의되면 한쪽만 고치는 사고가 난다 — 정의는 한 곳에만.
                if item["id"] in seen_ids and seen_ids[item["id"]] != f"{name}:{where}":
                    raise StackError(
                        f"id {item['id']!r} 가 두 곳에 정의됐다: "
                        f"{seen_ids[item['id']]} / {name}:{where}"
                    )
                seen_ids[item["id"]] = f"{name}:{where}"
        stacks[name] = data

    presets = _read(STACKS / "presets.yaml").get("presets") or {}
    aliases: dict[str, str] = {}
    for pname, p in presets.items():
        lang = p.get("lang")
        if lang not in stacks:
            raise StackError(f"프리셋 {pname}: 모르는 lang {lang!r}")
        for key in p.get("with") or []:
            if _find_optional(stacks, lang, key) is None:
                raise StackError(f"프리셋 {pname}: {lang} 도 common 도 {key!r} 를 모른다")
        for alias in [pname] + list(p.get("aliases") or []):
            if alias in aliases and aliases[alias] != pname:
                # 조용히 하나를 고르면 같은 말이 다른 조합으로 간다.
                raise StackError(f"alias {alias!r} 를 {aliases[alias]} 와 {pname} 가 함께 주장한다")
            aliases[alias] = pname
    return stacks, presets


def catalog_items() -> dict[str, dict]:
    """카탈로그 전체의 id → 항목. id 는 전역 유일임을 load() 가 보장한다.

    "이 분기가 아직 카탈로그에 있는가" 를 판정하는 근거다 — 프로젝트별 적용 기록 없이
    **다른 스택이 쓰는 분기**(유지)와 **은퇴한 항목**(제거)을 가른다.
    """
    all_stacks, _ = load()
    out: dict[str, dict] = {}
    for stack in all_stacks.values():
        blocks = [{"items": stack.get("base") or []}]
        blocks += [b or {} for b in (stack.get("optional") or {}).values()]
        for block in blocks:
            for item in _items_of(block):
                out[item["id"]] = item
    return out


def _find_optional(stacks: dict, lang: str, key: str) -> dict | None:
    """optional 키는 그 언어에서 찾고, 없으면 common 에서 찾는다."""
    for owner in (lang, "common"):
        block = ((stacks.get(owner) or {}).get("optional") or {}).get(key)
        if block is not None:
            return block or {}
    return None


def alias_map(presets: dict) -> dict[str, str]:
    out = {}
    for pname, p in presets.items():
        for alias in [pname] + list(p.get("aliases") or []):
            out[alias] = pname
    return out


# ------------------------------------------------------------------------ 해석

def resolve(spec: str, with_keys: list[str] | None = None) -> dict:
    """언어 이름 · 프리셋 이름 · alias 를 조합으로 펼친다.

    반환에는 배치될 항목(items)과 그 조합의 create·strips·verify·conflicts 가 들어간다.
    """
    stacks, presets = load()
    extra = list(with_keys or [])

    pname = alias_map(presets).get(spec)
    if pname:
        preset = presets[pname]
        lang, keys, title = preset["lang"], list(preset.get("with") or []), preset.get("title", pname)
        label = f"{pname} ({lang})"
    elif spec in stacks:
        lang, keys, title = spec, [], stacks[spec].get("title", spec)
        label = spec
    else:
        known = sorted(set(list(stacks) + list(alias_map(presets))))
        raise StackError(f"모르는 스택·프리셋 {spec!r}. 아는 것: {', '.join(known)}")

    for k in extra:
        if k not in keys:
            keys.append(k)

    # requires 를 **바뀌지 않을 때까지** 닫는다. 반복 횟수를 처음 키 개수로 묶으면 사슬이
    # 깊을 때 조용히 덜 닫힌다 — 오류 없이 항목 하나가 빠지는 형태다.
    grew = True
    while grew:
        grew = False
        for k in list(keys):
            block = _find_optional(stacks, lang, k)
            if block is None:
                raise StackError(f"{lang} 도 common 도 {k!r} 를 모른다")
            for dep in block.get("requires") or []:
                if dep not in keys:
                    keys.append(dep)
                    grew = True

    stack = stacks[lang]
    items: list[dict] = []
    creates: list[tuple[str, str]] = []
    strips: list[str] = []
    verify: list[str] = list(stack.get("verify") or [])

    def add(item: dict) -> None:
        if not any(i["id"] == item["id"] for i in items):
            items.append(item)

    for item in stack.get("base") or []:
        add(item)
    if stack.get("create"):
        creates.append((lang, stack["create"]))

    for k in keys:
        block = _find_optional(stacks, lang, k) or {}
        for item in _items_of(block):
            add(item)
        if block.get("create"):
            creates.append((k, block["create"]))
        strips += [s for s in (block.get("strips") or []) if s not in strips]
        verify += [v for v in (block.get("verify") or []) if v not in verify]

    # 스캐폴더가 둘이면 어느 쪽이 프로젝트를 만드는지 알 수 없다.
    scaffolds = [c for c in creates if c[0] != lang]
    if len(scaffolds) > 1:
        raise StackError(
            "스캐폴더가 둘이다: " + ", ".join(k for k, _ in scaffolds) +
            " — 한 번에 하나만 고른다"
        )
    create = (scaffolds or creates or [(None, None)])[0][1]

    # 같은 role 에 게이트가 둘이면 서로 다른 규칙으로 같은 파일을 판정한다.
    gates: dict[str, str] = {}
    for item in items:
        if item["surface"] == "gate":
            if item["role"] in gates:
                raise StackError(
                    f"role {item['role']!r} 에 게이트가 둘이다: "
                    f"{gates[item['role']]} / {item['id']} — 하나만 남긴다"
                )
            gates[item["role"]] = item["id"]

    conflicts = [tuple(c) for c in (stack.get("conflicts") or [])]
    conflicts += [tuple(c) for c in ((stacks.get("common") or {}).get("conflicts") or [])]

    return {
        "spec": spec, "label": label, "title": title, "lang": lang, "keys": keys,
        "items": items, "create": create, "strips": strips, "verify": verify,
        "normalize": stack.get("normalize"), "conflicts": conflicts,
        "strippable": stack.get("strippable") or {},
    }


# ------------------------------------------------------------------------ plan

def plan(combo: dict, target: Path) -> list[tuple[str, str]]:
    """실행할 셸 명령 목록. 스킬이 이것을 순서대로 돌린다 — 인자를 창작하지 않는다.

    **각 줄은 그 자체로 완결이다.** 예전에는 `cd <경로>` 를 한 줄로 내고 나머지가 그 셸을
    물려받는다고 가정했는데, 이 하네스의 에이전트는 Bash 호출마다 cwd 가 초기화된다 —
    그러면 install 이 엉뚱한 디렉터리로 간다. 그래서 프로젝트 안에서 돌아야 하는 줄은
    전부 `cd <경로> && …` 로 스스로를 고정한다.
    """
    steps: list[tuple[str, str]] = []
    if target.exists() and not target.is_dir():
        raise StackError(f"{target} 는 디렉터리가 아니다")
    empty = not target.exists() or not any(target.iterdir())
    created = bool(combo["create"]) and empty
    # 스킬은 이 줄을 **그대로** 실행한다. 공백이 든 경로(`~/My Projects/api`)를 안 감싸면
    # 모든 단계가 엉뚱한 디렉터리에서 돌거나 실패한다.
    q, qparent, qname = (shlex.quote(str(target)), shlex.quote(str(target.parent)),
                         shlex.quote(target.name))

    def inproj(cmd: str) -> str:
        return f"cd {q} && {cmd}"

    if created:
        # 경로를 못 다루는 스캐폴더가 있다 — nest 는 절대경로를 소문자로 낮추거나 상대경로로
        # 취급한다 [M]. 그런 경우 부모에서 이름만 주고 돌리므로 세 형태를 다 준다.
        steps.append(("create", combo["create"]
                      .replace("{dir}", q)
                      .replace("{parent}", qparent)
                      .replace("{name}", qname)))

    # strips 는 **스캐폴더가 방금 깐 것**을 지우는 단계다. create 를 건너뛴 기존 프로젝트에
    # 내면 `pnpm remove` 가 없는 의존성에 에러를 내며 계획이 중간에 죽는다 [M].
    if created:
        for sid in combo["strips"]:
            entry = combo["strippable"].get(sid) or {}
            if entry.get("remove"):
                steps.append(("strip", inproj(entry["remove"])))
            for f in entry.get("files") or []:
                steps.append(("strip", inproj(f"rm -f {f}")))

    for item in combo["items"]:
        if item.get("install"):
            steps.append(("install", inproj(item["install"])))
    for item in combo["items"]:
        if item.get("init"):
            steps.append(("init", inproj(item["init"])))

    # 선택 키를 그대로 다시 넘긴다 — 프리셋이 이미 포함하는 키여도 해석은 멱등이다.
    # 이 줄은 경로를 인자로 받으므로 cd 가 필요 없다.
    args = combo["spec"]
    if combo["keys"]:
        args += " --with " + ",".join(combo["keys"])
    steps.append(("apply", f"jig stack apply {args} {q} --apply"))

    # 스캐폴더·init 이 만든 파일을 우리 규칙으로 정리한다. **apply 뒤에 와야 한다** —
    # 설정 파일(biome.json 등)을 apply 가 배치하므로, 앞에 두면 도구 기본값으로 포맷한 뒤
    # 규칙이 바뀌어 verify 가 전부 실패한다 [M] (probe/results/stack-scaffold.md).
    if combo.get("normalize"):
        steps.append(("normalize", inproj(combo["normalize"])))

    for v in combo["verify"]:
        steps.append(("verify", inproj(v)))
    return steps


# ----------------------------------------------------------------------- check

def _pep508_name(spec: str) -> str:
    """`fastapi[standard]>=0.1` -> `fastapi`."""
    name = spec.strip()
    for sep in ("[", ">", "<", "=", "!", "~", ";", " ", "@"):
        name = name.split(sep)[0]
    return name.strip().lower()


def _deps(project: Path) -> set[str]:
    """선언된 의존성 이름. 잠금파일이 아니라 선언을 본다 — 사람이 고치는 쪽이다.

    선언 섹션만 파싱한다. 파일 전체에서 따옴표 문자열을 긁으면 `name = "x"` 같은 것까지
    의존성으로 세고, **없는 것을 있다고 말하는** 쪽으로 틀린다 — check 에서 가장 나쁜 방향이다.
    """
    names: set[str] = set()

    pkg = project / "package.json"
    if pkg.is_file():
        try:
            data = json.loads(pkg.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            data = {}
        if not isinstance(data, dict):     # 최상위가 배열인 package.json 도 파싱은 된다
            data = {}
        for key in ("dependencies", "devDependencies", "peerDependencies"):
            names |= {k.lower() for k in (data.get(key) or {})}

    pyproject = project / "pyproject.toml"
    if pyproject.is_file():
        try:
            data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
        except tomllib.TOMLDecodeError:
            data = {}
        buckets: list[list] = [(data.get("project") or {}).get("dependencies") or []]
        buckets += list(((data.get("project") or {}).get("optional-dependencies") or {}).values())
        buckets += list((data.get("dependency-groups") or {}).values())          # PEP 735 (uv)
        buckets.append(((data.get("tool") or {}).get("uv") or {}).get("dev-dependencies") or [])
        for bucket in buckets:
            names |= {_pep508_name(s) for s in bucket if isinstance(s, str)}
    return names


def _detected(spec: dict, project: Path, deps: set[str]) -> bool:
    if "dep" in spec:
        return str(spec["dep"]).lower() in deps
    if "file" in spec:
        return (project / spec["file"]).exists()
    if "mcp" in spec:
        return (MCP_DIR / f"{spec['mcp']}.json").is_file()
    return False


def active_ids(text: str) -> set[str]:
    """디스패처의 **생성물 구간 안에서 살아 있는** 분기 id.

    파일 전체를 문자열로 훑으면 사람이 주석 처리한 분기도 "있다" 고 세어 버린다 —
    체크의 false negative 는 이 장치에서 가장 나쁜 고장이므로 구간과 활성 여부를 본다.
    """
    if HOOK_MARKERS[0] not in text:
        return set()
    inside = text.split(HOOK_MARKERS[0], 1)[1].split(HOOK_MARKERS[1], 1)[0]
    found = set()
    for line in inside.splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        if m := ID_COMMENT.search(line):
            found.add(m.group(1))
    return found


def undetected(combo: dict, project: Path) -> list[str]:
    """조합 중 **프로젝트에 실제로 깔려 있지 않은** 항목. 표면이 배치됐는지는 보지 않는다.

    `apply` 는 훅·게이트를 배선할 뿐 도구를 깔지 않는다. 도구 없이 배선만 끝나면 증상은
    매 편집마다 나오는 stderr 뿐이라 아무도 눈치채지 못한다 — `check` 를 따로 부르지
    않는 사람에게도 그 자리에서 말해야 한다.
    """
    if not project.exists():
        return []
    deps = _deps(project)
    return [i["id"] for i in combo["items"]
            if i.get("detect") and not _detected(i["detect"], project, deps)]


def check(combo: dict, project: Path) -> list[tuple[str, str]]:
    """선언 ↔ 실제. 빠진 것과 충돌을 돌려준다. 빈 목록이면 조합대로 배치돼 있다."""
    if not project.exists():
        return [("(프로젝트)", f"{project} 가 없다")]

    deps = _deps(project)
    missing: list[tuple[str, str]] = []

    def ids_in(rel: str) -> set[str]:
        path = project / ".claude" / "hooks" / rel
        return active_ids(path.read_text(encoding="utf-8")) if path.is_file() else set()

    fmt_ids, gate_ids = ids_in("jig-format"), ids_in("jig-gate")

    for item in combo["items"]:
        iid, surface = item["id"], item["surface"]
        flagged = False
        if surface == "hook" and iid not in fmt_ids:
            missing.append((iid, "포맷 디스패처에 살아 있는 분기가 없다 — jig stack apply"))
            flagged = True
        elif surface == "gate" and iid not in gate_ids:
            missing.append((iid, "게이트 디스패처에 살아 있는 분기가 없다 — jig stack apply"))
            flagged = True
        elif surface == "mcp" and not (MCP_DIR / f"{iid}.json").is_file():
            missing.append((iid, f"library/mcp/{iid}.json 이 없다 — jig stack apply"))
            flagged = True

        # 표면 검사를 통과했어도 **도구가 깔렸는지는 따로 본다.** 예전에는 hook·gate·mcp 가
        # 표면 검사 뒤에 그대로 빠져나가서, 훅은 걸렸는데 ruff·pyright 가 안 깔린 프로젝트를
        # check 가 "ok" 라고 했다 — 매 편집마다 stderr 만 나오고 아무도 눈치채지 못하는,
        # 이 장치에서 가장 나쁜 방향의 고장이다.
        if not flagged and item.get("detect") and not _detected(item["detect"], project, deps):
            missing.append((iid, f"감지 실패: {item['detect']}"))

    # 빠진 것만 보면 반쪽이다 — **카탈로그에서 은퇴한 항목의 분기가 남아 계속 도는** 쪽도
    # 봐야 한다. 다른 스택이 쓰는 분기(카탈로그에 있고 표면이 맞는 것)는 정상이므로 뺀다.
    catalog = catalog_items()
    for rel, found, surface in (("jig-format", fmt_ids, "hook"),
                                ("jig-gate", gate_ids, "gate")):
        for iid in sorted(found):
            item = catalog.get(iid)
            if item is None or item["surface"] != surface:
                missing.append((iid, f".claude/hooks/{rel} 에 남아 있지만 카탈로그에 없다 "
                                     f"— jig stack apply 가 은퇴시킨다"))

    ours = {i["id"] for i in combo["items"]}
    for mine, theirs in combo["conflicts"]:
        if mine not in ours:
            continue
        spec = (combo["strippable"].get(theirs) or {}).get("detect") or {"dep": theirs}
        if _detected(spec, project, deps):
            missing.append((theirs, f"{mine} 와 충돌하는데 프로젝트에 남아 있다"))
    return missing


# ----------------------------------------------------------------------- 렌더

def _row(item: dict) -> str:
    why = str(item.get("why", "")).replace("|", "\\|")
    return f"| {item['role']} | `{item['id']}` | {item['surface']} | {why} |"


def _by_role(items: list[dict]) -> list[dict]:
    return sorted(items, key=lambda i: (ROLES.index(i["role"]), i["id"]))


def render_catalog() -> str:
    """`library/stacks/README.md` 의 카탈로그 블록. 언어별 → 기능별."""
    stacks, presets = load()
    out: list[str] = []

    for name in sorted(stacks):
        stack = stacks[name]
        out += ["", f"### {stack.get('title', name)} (`{name}`)", ""]
        base = _by_role(stack.get("base") or [])
        if base:
            out += ["**base** — 이 언어면 항상 들어간다", "",
                    "| 기능 | 도구 | 표면 | 근거 |", "|---|---|---|---|"]
            out += [_row(i) for i in base]
            out += [""]
        optional = stack.get("optional") or {}
        if optional:
            out += ["**optional** — `--with` 나 프리셋으로 고른다", "",
                    "| 키 | 기능 | 도구 | 표면 | 근거 |", "|---|---|---|---|---|"]
            for key in sorted(optional):
                for item in _by_role(_items_of(optional[key] or {})):
                    out.append(f"| `{key}` " + _row(item))
            out += [""]

    out += ["### 프리셋", "", "| 이름 | 언어 | 포함 | 이렇게 부르면 걸린다 |", "|---|---|---|---|"]
    for pname in sorted(presets):
        p = presets[pname]
        with_ = ", ".join(f"`{k}`" for k in p.get("with") or []) or "—"
        aliases = ", ".join(f"`{a}`" for a in p.get("aliases") or []) or "—"
        out.append(f"| **{pname}** | {p['lang']} | {with_} | {aliases} |")
    return "\n".join(out[1:] if out and out[0] == "" else out)


def list_lines() -> list[str]:
    stacks, presets = load()
    out = ["프리셋 — 이 이름이나 alias 로 부른다"]
    for pname in sorted(presets):
        p = presets[pname]
        out.append(f"  {pname:<10} {p['lang']:<11} {p.get('title', '')}")
        out.append(f"  {'':<10} + {', '.join(p.get('with') or []) or '(base 만)'}")
        out.append(f"  {'':<10} = {', '.join(p.get('aliases') or [])}")
    out += ["", "언어 스택 — 직접 부를 수도 있다"]
    for name in sorted(stacks):
        stack = stacks[name]
        nbase = len(stack.get("base") or [])
        keys = sorted((stack.get("optional") or {}))
        out.append(f"  {name:<11} base {nbase}개  optional: {', '.join(keys) or '없음'}")
    return out


def show_lines(combo: dict) -> list[str]:
    out = [f"{combo['label']} — {combo['title']}"]
    if combo["keys"]:
        out.append(f"  선택: {', '.join(combo['keys'])}")
    if combo["create"]:
        out.append(f"  스캐폴드: {combo['create']}")
    if combo["strips"]:
        out.append(f"  제거: {', '.join(combo['strips'])}")
    out.append("")

    for surface in SURFACES:
        mine = [i for i in _by_role(combo["items"]) if i["surface"] == surface]
        if not mine:
            continue
        note = {
            "hook": "  → 항목 하나(.claude/hooks/jig-format)의 분기로 들어간다",
            "gate": "  → 항목 하나(.claude/hooks/jig-gate)의 분기로 들어간다",
            "mcp": "  → library/mcp/<id>.json 만 만든다. 프로필에 켜는 것은 사람이 한다",
            "agents": "  → init 이 대상 프로젝트에 에이전트 정의를 만든다",
            "library": "  → 설치만. 에이전트 표면이 없다",
        }[surface]
        out.append(f"{surface}{note}")
        for item in mine:
            out.append(f"    {item['role']:<14} {item['id']}")
        out.append("")
    if combo["verify"]:
        out.append("verify")
        out += [f"    {v}" for v in combo["verify"]]
    return out
